import type { Metadata } from "next";
import { Inter, Kanit } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from '@/components/footer/Footer' 

const inter = Inter({ subsets: ["latin"] });
const kanit = Kanit({ subsets: ["latin"], weight: "500"  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
       <div  className="bg-[url('/skybg.jpg')] h-screen flex flex-col justify-between  overflow-auto">
       <div className="pt-10 pl-10 pr-10">
            <Navbar />
            {children}
          </div>
        <Footer/>
        </div>
        </body>
    </html>
  );
}
